### ISSUE TITLE
animating the progress bar

### ISSUE THREAD

**Issue by jotasgarcia** [crisbeto/angular-svg-round-progressbar#107]
Hi, 

I have some _slides_ with transitions, one of them includes your progressbar:

http://jsfiddle.net/jotasgarcia/hk8kfo0r/

When you run the code you will see the animtation. I want to know how to fire the animation everytime the progress bar is shown and not just the first time.

Can you please help me?

**Comment by crisbeto** [comment]
You can reset your current progress to 0 and then re-animate it when the slide becomes visible again.

**Comment by jotasgarcia** [comment]
Yes, but I dont know how to re-animate the progressbar. If I change the current value it displays it but with no animation.

**Comment by crisbeto** [comment]
Not sure what you mean, the value should get animated every time you change it.

**Comment by jotasgarcia** [comment]
The value or animation of the progress filling is done once it is a slide changed and it returns to the slide where the progress is only done when one reloads the rest page does not do it again, and what I need is that If you re-animate the value and fill in the progress once you are back on the slide you can help me please with the code this is the code that I have : http://jsfiddle.net/jotasgarcia/hk8kfo0r/

**Comment by jotasgarcia** [comment]
The value or animation of the progress filling is done once it is a slide changed and it returns to the slide where the progress is only done when one reloads the rest page does not do it again, and what I need is that If you re-animate the value and fill in the progress once you are back on the slide you can help me please with the code this is the code that I have : http://jsfiddle.net/jotasgarcia/hk8kfo0r/

**Comment by crisbeto** [comment]
Sorry, I've been pretty busy. What is happening in your slider is that you render the progress bar once and you hide it afterwards. You need to reset the `current` value in order to reboot the animation. [Here's a forked fiddle that shows what you want to achieve.](http://jsfiddle.net/v7228m08/2/) The only changes that I've done is to add the following to the `beforeChange` event. Note that you'll probably need to change up the logic if you add more slides, but it should be enough to get the idea:

```js
$scope.$apply(function() {
  $scope.current = currentSlide === 0 ? 0 : 80;
});
```

**Comment by jotasgarcia** [comment]
Great! Thank you very much : )
