### ISSUE TITLE
color ramp transition

### ISSUE THREAD

**Issue by DreadKnight** [crisbeto/angular-svg-round-progressbar#14]
I'm wondering if there's an easy way to set specific bar colors for various percentages similar to what I'm doing over here, currently using the old spritesheet technique http://ancientbeast.com/units/#Miss_Creeper

**Comment by crisbeto** [comment]
Yes you can, assuming your progressbar looks something like this (note that only the `color` matters):
```html
<div
    round-progress
    max="max"
    current="current"
    color="{{ defaultColor }}"></div>
```

You can have any data binding in the `color` attribute, so you have two options:

1. You can do the logic inline. This isn't recommended since you can't do more advanced logic and it can get messy:
 ```html
<div
    round-progress
    max="max"
    current="current"
    color="{{ current < 50 : '#f00' : '#0f0' }}"></div>
```

2. You can also have a function that determines the color (recommended):
 ```html
<div
    round-progress
    max="max"
    current="current"
    color="{{ getCurrentColor(current) }}"></div>
```

And in your controller:
```javascript
$scope.getCurrentColor = function(current){
    if(current > 30){
        return '#f00';
    }else if(current > 10){
        return '#0f0';
    }else{
        return '#00f';
    }
};
```

**Bonus!** If you want a transition between the colors, you can add this to your CSS:
```css
path{
    transition: stroke .3s ease;
}
```

**Comment by DreadKnight** [comment]
Big thanks! Will give option 2 a go pretty soon and yeah, I was definitely looking for color transitions.
