### ISSUE TITLE
Can we add a border?

### ISSUE THREAD

**Issue by shraddha1112** [crisbeto/angular-svg-round-progressbar#18]
Hello, 
I wanted to add border to this circle both from inside and outside. Is there a way to customize? If yes then how?

Regards,
Shraddha

**Comment by crisbeto** [comment]
Its not possible at the moment since the "current" progress is being drawn the stroke SVG property. 
It also gives some strange results with CSS http://prntscr.com/6zfmtg. I think it might be possible with http://stackoverflow.com/questions/12723832/how-can-i-implement-offset-path-effect-in-svg-without-using-javascript-or-dilate but I don't the time to try it out, at the moment.

**Comment by crisbeto** [comment]
Well it's been over a year. I actually tried it out, at some point, but it wasn't feasible.
