### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by DuncanFaulkner** [crisbeto/angular-svg-round-progressbar#196]
Just wondering if this is still being maintained as last release was Sept 2019, there were some issues with version 8 of Angular compiling with Ivy, just wondering if these have been sorted or being worked on now version 9 of Angular is out?

**Comment by crisbeto** [comment]
I'm definitely maintaining it, but I haven't released since September since the module isn't doing anything fancy and it doesn't need any changes for new versions of Angular. At some point I need to switch the build away from my current custom setup to `ng-packagr`, but I haven't had the time to do it yet.

**Comment by DuncanFaulkner** [comment]
OK thanks, do we know if this works with Angular 9 and Ivy?

**Comment by crisbeto** [comment]
I haven't tried it myself yet, but I expect it to work since it isn't hitting any of the breaking changes.

**Comment by DuncanFaulkner** [comment]
OK, will let you know if I have a problem cheers
