### ISSUE TITLE
incompatible peer dependency to "zone.js" (requires "^0.9.0", would install "0.10.3")

### ISSUE THREAD

**Issue by gvlekke** [crisbeto/angular-svg-round-progressbar#199]
When I use `ng update @angular/cli` i get this error:

`Package "angular-svg-round-progressbar" has an incompatible peer dependency to "zone.js" (requires "^0.9.0", would install "0.10.3").`

maybe a good idea to widen the peer dependencies a bit?

**Comment by crisbeto** [comment]
Hmm, I would've expected for the `^0.9.0` to cover `0.10.3` as well.

**Comment by gvlekke** [comment]
yeah thats weird, sometimes you also see some peer dependencies in the package json doesn't know if that helps.

**Comment by JorisDebonnet** [comment]
A little SemVer lesson 😄

`^1.9.0` covers `^1.10.3`, but `^0.9.0` does not cover `^0.10.3`. That's because of the 0 at the start. SemVer then considers the next number to be 'backwards incompatible changes', and so upgrades from 0.9 to 0.10 are prevented, just like an upgrade from 9 to 10 would be prevented. 

A way to fix that is to test and make sure zone.js `0.10` causes no issues, and then change the requested version into `>=0.9.0 <0.11.0` instead of `^0.9.0`.

Anyhow, I guess this issue is out of date since the current master of this repository requests zone.js `^0.10.3`.

**Comment by gvlekke** [comment]
@JorisDebonnet could be that its outdated, will close it for now
