### ISSUE TITLE
[Feature Request] Partial colors

### ISSUE THREAD

**Issue by felipecocco** [crisbeto/angular-svg-round-progressbar#29]
Would be a fantastic tool for data displays if the stroke could be filled with several different colors. I did notice that you can dynamically change the fill of the entire stroke, but it would be even more amazing if you could have it so that part of it would be a certain color and part of it another.

**Comment by crisbeto** [comment]
Good idea, although it probably wouldn't be practical to add it as an attribute option. Should work well with transclusion and allowing users to specify the gradient themselves.

**Comment by crisbeto** [comment]
Done in the [0.2.8 release](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.2.8), here's an example of how to do it:

```html
<div
    round-progress
    max="100"
    current="20"
    color="url(#yourGradientIdHere)">
    
    <svg>
        <linearGradient id="yourGradientIdHere" x1="0" x2="0" y1="0" y2="1">
            <stop offset="5%"  stop-color="green"/>
            <stop offset="95%" stop-color="gold"/>
        </linearGradient>
    </svg>
</div>
```

A couple of notes:
* You should specify your gradient element as a child of your `round-progress` element. 
* The gradient element has to be wrapped in an `svg` element, otherwise it won't work.
* You need to specify an id on your gradient element.
* You need to specify the gradient id in the `color` attribute as `url(#yourGradientId)`.

Some more info about SVG gradients: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients
