### ISSUE TITLE
Nested progress bars?

### ISSUE THREAD

**Issue by RobertHerhold** [crisbeto/angular-svg-round-progressbar#38]
I realize this would require an immense amount of re-writing, but do you think it would be possible to have individually-configurable nested progress bars?

**Comment by crisbeto** [comment]
Technically it should be possible, because svg allows nesting other svg elements, although after a bit of fiddling around I found a couple of problems:

1. The directive is using `.find` to get a hold of the path and the circle, if there's another nested svg, it picks up its children as well. This can be fixed easily.

2. Angular throws an error if one round progressbar is nested into another. I believe its because Angular can't find the element because it gets transcluded. I'm not quite sure how to fix this one.

**Comment by crisbeto** [comment]
It has been a while since this issue was posted, but with the changes in https://github.com/crisbeto/angular-svg-round-progressbar/commit/4af45d3293bbfacd9b39782bfff8ec7003e77cb3 it's now possible to nest progressbars. I'm working on making this a little more convenient, but here's what can be done now:

![2015-10-11_16-45-30](https://cloud.githubusercontent.com/assets/4450522/10417318/8850cd84-7037-11e5-8d63-9da2d2eb26e0.png)

**Comment by RobertHerhold** [comment]
That looks amazing! Thanks for implementing this :)

**Comment by crisbeto** [comment]
Released in [0.3.6](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.3.6)

**Comment by JCMais** [comment]
@crisbeto Would it be possible to have something like this

![knob](http://i.stack.imgur.com/s5P09.png)

**Comment by crisbeto** [comment]
You might have some luck with nesting a few progressbars and adding a rotation to the path, but I think built-in support is out of the scope of the project. Your example is more of chart than a progressbar.

**Comment by JCMais** [comment]
In reality they are multiple progress bar stacked one after the other, think on it as a queue. I will take a look on what you said.

**Comment by JosnaPriyaPereira** [comment]
@crisbeto , I am using below code to nest 2 round progress bars.

  <round-progress
                max="100"
                current="20"
                color="red">
                
                <round-progress max="100"
                    current="20"
                    color="blue"  offset="30"></round-progress></round-progress>
The progress bars display fine in chrome simulator in Ios devices, but only the outer bar appears in xcode iphone simulator. Also only a single bar appears in the actual ios device. 

Can you please help?

**Comment by knx-am** [comment]
@crisbeto Is this feature supposed to be still working in the Angular 1 version (0.4.8)?
I tried it but the bars are rendered above each other. The inner svg does not have the viewBox attribute but that has no effect. Am I missing something?
Thanks for helping

**Comment by crisbeto** [comment]
You can try setting the `offset` option to `"inherit"` which should prevent the progress bars from going beneath each other.

**Comment by knx-am** [comment]
I copied the example from build/index.html and adjusted it and now it works!
I tried the offset attribute before and it didn't help. I was probably doing something else wrong.
Thanks again

**Comment by khaled9544** [comment]
is this feature is still available?

**Comment by crisbeto** [comment]
@khaled9544 it was available on the AngularJS version of the component, but I haven't ported it to Angular yet.

**Comment by jongbonga** [comment]
> @khaled9544 it was available on the AngularJS version of the component, but I haven't ported it to Angular yet.

Hi @crisbeto thanks for the plugin.

Any luck with this?
