### ISSUE TITLE
When value changed

### ISSUE THREAD

**Issue by sommerce** [crisbeto/angular-svg-round-progressbar#54]
What about an event or callback to know when counter value changed (1,2,3,4,5,6,...)?
Parent controller will know each time value changing and can use to output current value or calculate percentage or whatever consumer want to display.

**Comment by crisbeto** [comment]
Makes sense. I'll see what I can do.

**Comment by crisbeto** [comment]
@sommerce I've added this to the [0.3.10 release](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.3.10). 

You can use it by adding a function to your controller:

```js
$scope.test = function(currentAmount, options, element){
  console.log(currentAmount, options, element);
}
```

Afterwards you need to pass that function to the directive using the `on-render` attribute:

```html
<div round-progress on-render="test"></div>
```

Now every time the circle gets rendered, you'll get the current percentage, the options that were being used to render the circle and the wrapper element. Keep in mind that if you're going to use that info in the controller, you'll have to trigger a `$digest` yourself since the directive doesn't trigger one for each frame.

**Comment by sommerce** [comment]
Kristiyan, thank you so much)))
I'll try it right now!

**Comment by sommerce** [comment]
Works like a charm)
$digest() and $apply() caused error "$digest already in progress", so I used defer

**Comment by crisbeto** [comment]
Yeah, usually the first digest will have already started because the value just changed, however the next updates won't cause the digest. I usually resolve to using a `$timeout` in those cases, but a deferred should work as well. [Here's what I did in the demo](https://github.com/crisbeto/angular-svg-round-progressbar/blob/master/build/index.html#L340). 

Also should I consider the issue resolved?
