### ISSUE TITLE
Ability to style colors via CSS?

### ISSUE THREAD

**Issue by Voziv** [crisbeto/angular-svg-round-progressbar#61]
It'd be great to be able to style the bar via CSS. Currently I had to comment out the css setting code. The reason we do this is because we theme a site via LESS files which derive their colors from LESS variables.

```js
ring.css({
//    "stroke"         : service.resolveColor(options.color),
//    "stroke-width"   : stroke,
    "stroke-linecap" : options.rounded ? "round" : "butt"
});
```

And the background css as well

```js
background.attr({
    "cx" : radius,
    "cy" : radius,
    "r"  : backgroundSize >= 0 ? backgroundSize : 0
});
// .css({
//     "stroke"       : service.resolveColor(options.bgcolor),
//     "stroke-width" : stroke
// });
```

**Comment by crisbeto** [comment]
The reason I went with adding it with JS was because I didn't want people to have to include extra CSS. This might be a bit of a hack, but you have two options:

1. Overriding the color with `!important`, which might be a bad idea for specificity.
2. If you set an invalid color, the CSS color will take precedence. E.g. you can put in an empty string to `roundProgressConfig` and it will always take your CSS colors:

```javascript
angular.module('yourApp', ['angular-svg-round-progress'], ['roundProgressConfig', function(roundProgressConfig){
  roundProgressConfig.color = '';
}]);
```

```css
[round-progress] path{
  stroke: #f00;
}
```

**Comment by Voziv** [comment]
I didn't want it to add in a style declaration that would be potentially invalid. I was hoping more for a way to disable the addition of the css additions entirely using the config. I may have time to send off a PR tomorrow with something like this

**Comment by crisbeto** [comment]
I don't think I could accept that PR since it opens the door to having all sorts of flags for disabling random stuff.

**Comment by Voziv** [comment]
No problem
