### ISSUE TITLE
For install - dependency name is angular-svg-round-progressbar

### ISSUE THREAD

**Issue by lyurko** [crisbeto/angular-svg-round-progressbar#62]
The install notes say to add to dependencies "angular-svg-round-progress" - by making the name "angular-svg-round-progressbar" in bower.json it fixed installation issues for anyone else running into this problem.

Pretty straightforward but wanted to help save anyone else time.

**Comment by crisbeto** [comment]
Nice catch. I'll add it to the readme.

**Comment by crisbeto** [comment]
Actually not sure how I didn't notice this until now, but I registered the package as "progressbar", but the module is named "progress". I'll have to rename it so it matches.

**Comment by crisbeto** [comment]
I've released [0.4.0](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.4.0) to address this and a few other minor issues.

**Comment by cded** [comment]
Hi we're a small business starting in Montreal and we use your progress bar in our app. We made the mistake of using a link to your github repository for roundProgress.js instead of downloading it. When you changed the module name to progressbar instead of progress it made the whole app crash. It takes a few days for the app store to process an update. Could you change the name back for a few days? It would be much appreciated.

**Comment by crisbeto** [comment]
Reverting a release would be a bit of a pain, but let me see if I can create a temporary proxy module.

**Comment by cded** [comment]
That would be amazing, thank you.

**Comment by crisbeto** [comment]
There you go. I'll remove the proxy module on May 1st.

**Comment by cded** [comment]
Thanks a lot man! it works now
