### ISSUE TITLE
center value is not appear

### ISSUE THREAD

**Issue by anilkumarsoni** [crisbeto/angular-svg-round-progressbar#96]
max and current value is not appear in center like "27/50"

**Comment by crisbeto** [comment]
It's not supposed to. I deliberately didn't add the text feature because there are so many different ways in which to approach it. [You can refer to this comment on how to do it yourself](https://github.com/crisbeto/angular-svg-round-progressbar/issues/55#issuecomment-173504646) or you can check out the [demo's source code](https://github.com/crisbeto/angular-svg-round-progressbar/tree/master/build).
